services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: anime_ecommerce_backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    networks:
      - gemini-dashboard-test_default

networks:
  gemini-dashboard-test_default:
    external: true
